### ISSUE TITLE
Wrong rebase-conflict example

### ISSUE THREAD

**Issue by nimlock** [netology-code/sysadm-homeworks#8]
@andrey-borue , при выполнении ДЗ 02-git-03-branching заметил, что в свежих коммитах master затёрт верный пример конфликта при выполнении rebase - https://github.com/netology-code/sysadm-homeworks/blame/master/02-git-03-branching/README.md#L149-L159.

Всё было верно в коммите c3c5474f6942da9b979a98683cc5169168668907 - https://github.com/netology-code/sysadm-homeworks/blame/c3c5474f6942da9b979a98683cc5169168668907/02-git-03-branching/README.md#L145-L159.

Создал ветку с исправлением для открытия PR, но пуш на Гитхаб запрещён, а иного способа открытия PR не знаю. Видел что вроде можно сделать форк репозтоиря и делать PR из него, но что-то это слишком громоздко для одной правки.

С уважением, Иван Жиляев

**Comment by FactorT** [comment]
@andrey-borue Товарищ дело говорит. В ДЗ ошибка.

**Comment by andrey-borue** [comment]
Fixed
